### ISSUE TITLE
Feature request: choose environment for ddev pull

### ISSUE THREAD

**Issue by gilzow** [platformsh/ddev-platformsh#63] opened 2022-11-15 20:53 UTC
**Feature request**:
With the `ddev pull platform` command prompt the user for the environment they wish to pull from, defaulting to the current checked out branch.

**Reasoning**:
Often when working with colleagues, we need to debug/troubleshoot a feature we're developing in a non-production branch. This often involves needing to sync that environment's database into the local development environment to further work on. The current implementation of `ddev pull platform` limits the user to the environment they choose during the initial `ddev get platformsh/ddev-platformsh` or manually updating the `.ddev/config.yaml` file.    

Ideally, when initiating the `ddev pull platform` command, the user would be given a choice of currently active platform.sh environments, with the default selection matching the current locally checked out environment. This would allow for users to quickly and easily replicate platform.sh environments locally without having to manually update files.

**Comment by rfay** [comment] 2022-11-15 21:13
Thanks, Duplicate of 
* https://github.com/drud/ddev/issues/4180

**Comment by gilzow** [comment] 2022-11-16 19:03
apologies. I did not post in ddev/ddev since I thought this was/is unique to this add-on. I'll respond over there.

**Closed** 2022-11-28 23:46 UTC
